version: "3"
services:
  laravel:
    build: .
    ports:
      - "4000:80"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
       - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=laravel
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
volumes:
  db-data: